# Generated by Django 5.2 on 2025-04-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('client', 'program')},
        ),
    ]
